version: "3.8"

services:
  app:
    image: us-docker.pkg.dev/fifth-medley-478216-a7/docker/python-app:v1
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
