---
###################################
# INITIALIZE SWARM ON MANAGER NODE
###################################
- name: Initialize Docker Swarm on Manager
  hosts: manager
  become: yes
  tasks:

    - name: Leave old swarm if exists
      shell: docker swarm leave --force
      ignore_errors: yes

    - name: Remove old swarm directory if exists
      shell: rm -rf /var/lib/docker/swarm
      ignore_errors: yes

    - name: Initialize swarm
      shell: docker swarm init --advertise-addr {{ ansible_host }}

    - name: Get worker join token
      shell: docker swarm join-token -q worker
      register: worker_token

    - name: Save join-token
      set_fact:
        join_token: "{{ worker_token.stdout }}"


#########################################
# RESET & JOIN WORKERS
#########################################
- name: Join workers to Docker Swarm
  hosts: workers
  become: yes
  tasks:

    - name: Leave old swarm if exists
      shell: docker swarm leave --force
      ignore_errors: yes

    - name: Remove old swarm directory
      shell: rm -rf /var/lib/docker/swarm
      ignore_errors: yes

    - name: Join worker to new swarm
      shell: docker swarm join --token {{ hostvars['manager']['join_token'] }} {{ hostvars['manager']['ansible_host'] }}:2377


#########################################
# CLONE GIT REPO & DEPLOY STACK
#########################################
- name: Clone Repo & Deploy Stack
  hosts: manager
  become: yes
  vars:
    repo_url: "https://github.com/venkat-6666/docker-swarm.git"
    repo_path: "/opt/docker-swarm"
    stack_file: "docker-stack.yaml"
    stack_name: "mystack"
  tasks:

    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone or update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        force: yes

    - name: Deploy Docker stack
      shell: docker stack deploy -c {{ repo_path }}/{{ stack_file }} {{ stack_name }}
