---
###################################
# INITIALIZE SWARM ON MANAGER NODE
###################################
- name: Initialize Docker Swarm on Manager
  hosts: manager
  become: yes
  tasks:

    - name: Initialize swarm (only if not already initialized)
      shell: docker swarm init --advertise-addr {{ ansible_host }}
      args:
        creates: /var/lib/docker/swarm

    - name: Get worker join token
      shell: docker swarm join-token -q worker
      register: worker_token

    - name: Save token to hostvars
      set_fact:
        join_token: "{{ worker_token.stdout }}"


#########################################
# JOIN WORKERS TO THE SWARM
#########################################
- name: Join workers to Docker Swarm
  hosts: workers
  become: yes
  tasks:

    - name: Join worker to Swarm
      shell: docker swarm join --token {{ hostvars['manager']['join_token'] }} {{ hostvars['manager']['ansible_host'] }}:2377
      args:
        creates: /var/lib/docker/swarm


#########################################
# CLONE REPO & DEPLOY STACK ON MANAGER
#########################################
- name: Clone Repo and Deploy Stack
  hosts: manager
  become: yes
  vars:
    repo_url: "https://github.com/venkat-6666/docker-swarm.git"   # <-- UPDATED
    repo_path: "/opt/docker-swarm"
    stack_file: "docker-stack.yaml"         # <-- your file name
    stack_name: "mystack"
  tasks:

    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone or update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: main
        force: yes

    - name: Deploy Docker stack using docker-stack.yaml
      shell: docker stack deploy -c {{ repo_path }}/{{ stack_file }} {{ stack_name }}
